package com.gazi.gazi_renew.mock;

import com.gazi.gazi_renew.route.domain.MyFindRoadSubPath;
import com.gazi.gazi_renew.route.service.port.MyFindRoadSubPathRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMyFindRoadSubPathRepository implements MyFindRoadSubPathRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<MyFindRoadSubPath> data = new ArrayList<>();
    @Override
    public MyFindRoadSubPath save(MyFindRoadSubPath myFindRoadSubPath) {
        if (myFindRoadSubPath.getId() == null || myFindRoadSubPath.getId() == 0) {
            MyFindRoadSubPath createSubPath = MyFindRoadSubPath.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .trafficType(myFindRoadSubPath.getTrafficType())
                    .distance(myFindRoadSubPath.getDistance())
                    .sectionTime(myFindRoadSubPath.getSectionTime())
                    .stationCount(myFindRoadSubPath.getStationCount())
                    .way(myFindRoadSubPath.getWay())
                    .door(myFindRoadSubPath.getDoor())
                    .lanes(myFindRoadSubPath.getLanes())
                    .stations(myFindRoadSubPath.getStations())
                    .build();
            data.add(createSubPath);
            return createSubPath;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), myFindRoadSubPath.getId()));
            data.add(myFindRoadSubPath);
            return myFindRoadSubPath;
        }
    }
}
